highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
permalink: blogs/:title/
title: Praveen Korukonda
email: me@praveenk.dev
description: Website of Praveen Korukonda
keywords: praveen,korukonda,iit,roorkee,developer,programmer,github
baseurl: ""
url: https://praveenk.dev
name: Praveen Korukonda\'s Website
author:
  name: Praveen Korukonda
  email: me@praveenk.dev
cloudflare_analytics_token: "6d803f14a158461d9c9366e27e717372"
